name: deploy-payroll

on:
  push:
    branches: [ "master" ]
    paths:
      - "go-EMS-payrollService/**"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.21.3'
      id: install


    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Building docker image
      run: cd go-EMS-payrollService  && docker build -t yashjindal28/go-ems-payrollservice . 


    - name: Login to docker hub
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}

    - name: Pushing image to docker hub 
      run: docker push yashjindal28/go-ems-payrollservice

    - name: Update kube config
      run: aws eks update-kubeconfig --name employee-management-system --region ap-south-1

    - name: Deploy image to Amazon EKS
      run:  kubectl rollout restart deployment payrollservice-deployment